# /etc/nginx/snippets/rizky-ssl.conf
ssl_certificate     /etc/letsencrypt/live/rizky.com/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/rizky.com/privkey.pem;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_session_cache shared:SSL:10m;
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
add_header X-Content-Type-Options nosniff always;
